services:
   backend:
      build:
         context: ./backend
         dockerfile: Dockerfile
      container_name: skillswap-backend
      ports:
         - '0.0.0.0:8080:8080'
      environment:
         - DB_URL=/root/data/skillswap.db
         - GOMEMLIMIT=64MiB
      volumes:
         - backend-uploads:/root/uploads
         - backend-data:/root/data
      networks:
         skillswap-network:
            aliases:
               - backend
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 128M

   frontend:
      build:
         context: ./frontend
         dockerfile: Dockerfile
         shm_size: '1gb'
      container_name: skillswap-frontend
      ports:
         - '0.0.0.0:80:3000'
      environment:
         - ORIGIN=http://89.117.50.20
         - BODY_SIZE_LIMIT=Infinity
         - BACKEND_URL=http://backend:8080
         - NODE_OPTIONS=--max-old-space-size=256
      depends_on:
         backend:
            condition: service_started
      networks:
         - skillswap-network
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 512M
            reservations:
               memory: 128M

   updater:
      image: containrrr/watchtower
      container_name: skillswap-updater
      profiles: ['manual']
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./:/app
      environment:
         - WATCHTOWER_CLEANUP=true
         - WATCHTOWER_INCLUDE_STOPPED=true
         - WATCHTOWER_POLL_INTERVAL=300
      command: --run-once=false
      networks:
         - skillswap-network
      restart: unless-stopped

   autoupdate:
      image: alpine/git
      container_name: skillswap-git-puller
      profiles: ['manual']
      working_dir: /app
      volumes:
         - ./:/app
      entrypoint: /bin/sh
      command: -c "while true; do git fetch origin && git reset --hard origin/main && sleep 300; done"
      restart: unless-stopped
      networks:
         - skillswap-network

networks:
   skillswap-network:
      driver: bridge

volumes:
   backend-data:
   backend-uploads:
