DROP DATABASE IF EXISTS skillswap;
CREATE DATABASE IF NOT EXISTS skillswap;
USE skillswap;


CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    profile_picture VARCHAR(255),
    aboutme TEXT,
    projects TEXT,
    contacts TEXT,
    skills TEXT,
    location TEXT,

    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skills (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS user_skills (
    user_id INT NOT null,
    skill_id INT NOT NULL,
    teaching_skill ENUM("Show how it's done", "Explain in slight details", "Give homework report on subject", "Professor") DEFAULT "Show how it's done",
    verified BOOL DEFAULT FALSE,
    PRIMARY KEY (user_id, skill_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS chats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user1_id INT NOT null,
    user2_id INT NOT null,
    initiated_by INT NOT null,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (initiated_by) REFERENCES users(id) ON DELETE CASCADE,
	 FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chat_id INT NOT null,
    sender_id INT NOT null,
    content TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNIQUE NOT null,
    session_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


Insert Into users ( id, username, email, password_hash, profile_picture, aboutme, contacts, skills, location, projects) Values
    ( 1,'Lesly','Lesly.1@gmail.com','eRYFjg7IjuOQLFM5Gn937OI18adGpu1U','http://localhost:8080/file/profile/Lesly','eXsDWbouaxSvOUXEaiG','{"name":"Lesly Lesly.1@gmail.com","email":"lesly.lesly.1@gmail.com@example.com","twitter":"@lesly642","linkedin":"linkedin.com/in/lesly-lesly.1@gmail.com"}','Database Administrator & Web Developer','Durban','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project4"}]' ),
    ( 2,'Concettina','Concettina.2@gmail.com','3AtfruvXzdcVXiTlpPIHc1cLU1nE9hWj','http://localhost:8080/file/profile/Concettina','WByqAmJVGlOutqvhiqCJUpVYS','{"name":"Concettina Concettina.2@gmail.com","email":"concettina.concettina.2@gmail.com@example.com","twitter":"@concettina944","linkedin":"linkedin.com/in/concettina-concettina.2@gmail.com"}','Financial Analyst & Animator','Manzini','[]' ),
    ( 3,'Sashenka','Sashenka.3@gmail.com','uY97t9Okcz4fIYi9STeuqOTBckiWdoec','http://localhost:8080/file/profile/Sashenka','wtAdkDbEOoxWPlVevf','{"name":"Sashenka Sashenka.3@gmail.com","email":"sashenka.sashenka.3@gmail.com@example.com","twitter":"@sashenka732","linkedin":"linkedin.com/in/sashenka-sashenka.3@gmail.com"}','Public Relations Specialist & Web Developer','Rabat','[{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 4,'Meg','Meg.4@gmail.com','JYPSsIcRxLo3G9TxlwUQj3UVJTL8q8L1','http://localhost:8080/file/profile/Meg','TCQUrCXAqfTcxZvqDgIQjKHuwrOoHf','{"name":"Meg Meg.4@gmail.com","email":"meg.meg.4@gmail.com@example.com","twitter":"@meg582","linkedin":"linkedin.com/in/meg-meg.4@gmail.com"}','Scrum Master & Communications Manager','Muscat','[{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 5,'Ann-Marie','Ann-Marie.5@gmail.com','sFTdQqe5VS20Hcz2uHRdWjCJ3FXXFtNr','http://localhost:8080/file/profile/Ann-Marie','IdwVZqDfYXqToORN','{"name":"Ann-Marie Ann-Marie.5@gmail.com","email":"ann-marie.ann-marie.5@gmail.com@example.com","twitter":"@ann-marie390","linkedin":"linkedin.com/in/ann-marie-ann-marie.5@gmail.com"}','Operations Manager & Back-End Developer','Zanzibar City','[{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project4"}]' ),
    ( 6,'Joelly','Joelly.6@gmail.com','EHSbPL6OSrbWGgGcBrTVlhOX3eLocTW8','http://localhost:8080/file/profile/Joelly','oOk','{"name":"Joelly Joelly.6@gmail.com","email":"joelly.joelly.6@gmail.com@example.com","twitter":"@joelly441","linkedin":"linkedin.com/in/joelly-joelly.6@gmail.com"}','Business Intelligence Analyst & Web Developer','Taipei','[]' ),
    ( 7,'Alyda','Alyda.7@gmail.com','EJkWlc8sCF4ANOZ8SDiwJ4cWvmEwradk','http://localhost:8080/file/profile/Alyda','bqXr','{"name":"Alyda Alyda.7@gmail.com","email":"alyda.alyda.7@gmail.com@example.com","twitter":"@alyda647","linkedin":"linkedin.com/in/alyda-alyda.7@gmail.com"}','Data Scientist & Communications Manager','Brasília','[]' ),
    ( 8,'Jenda','Jenda.8@gmail.com','ZAQhwbZaHuGjvuaqmKI4igrkeFejh5RH','http://localhost:8080/file/profile/Jenda','LHZJcyVASI','{"name":"Jenda Jenda.8@gmail.com","email":"jenda.jenda.8@gmail.com@example.com","twitter":"@jenda827","linkedin":"linkedin.com/in/jenda-jenda.8@gmail.com"}','Public Relations Specialist & Data Analyst','Zamboanga City','[]' ),
    ( 9,'Ada','Ada.9@gmail.com','fZFPeEonJKwgftC9INhXjG8gX6coyoE0','http://localhost:8080/file/profile/Ada','Dk','{"name":"Ada Ada.9@gmail.com","email":"ada.ada.9@gmail.com@example.com","twitter":"@ada23","linkedin":"linkedin.com/in/ada-ada.9@gmail.com"}','Communications Manager & Brand Strategist','Oslo','[]' ),
    ( 10,'Michaelina','Michaelina.10@gmail.com','4raO6qvtMOV9u1u9wcRp2EgcoUZ4G7bS','http://localhost:8080/file/profile/Michaelina','HOJIVjwAvBaiiXCdfgc','{"name":"Michaelina Michaelina.10@gmail.com","email":"michaelina.michaelina.10@gmail.com@example.com","twitter":"@michaelina728","linkedin":"linkedin.com/in/michaelina-michaelina.10@gmail.com"}','Product Manager & Machine Learning Engineer','Phuket (city)','[]' ),
    ( 11,'Harmonia','Harmonia.11@gmail.com','djzJAidrAesVRggyRdB6aHPQDD0jEtA0','http://localhost:8080/file/profile/Harmonia','cYAMJLqsDEKfpyfC','{"name":"Harmonia Harmonia.11@gmail.com","email":"harmonia.harmonia.11@gmail.com@example.com","twitter":"@harmonia142","linkedin":"linkedin.com/in/harmonia-harmonia.11@gmail.com"}','Machine Learning Engineer & SEO Specialist','Port Hedland','[{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"}]' ),
    ( 12,'Beth','Beth.12@gmail.com','GPnuIHomMa5jywRok3suNIRu83gtcboz','http://localhost:8080/file/profile/Beth','EnODuUn','{"name":"Beth Beth.12@gmail.com","email":"beth.beth.12@gmail.com@example.com","twitter":"@beth734","linkedin":"linkedin.com/in/beth-beth.12@gmail.com"}','Packaging Designer & Financial Analyst','Hai Phong','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"}]' ),
    ( 13,'Jenilee','Jenilee.13@gmail.com','EKXSR5muJm9MooQkMYpJ3IdSTU0DXdV0','http://localhost:8080/file/profile/Jenilee','QpOGxHTnKJtQDJIiXOGsyFflkka','{"name":"Jenilee Jenilee.13@gmail.com","email":"jenilee.jenilee.13@gmail.com@example.com","twitter":"@jenilee499","linkedin":"linkedin.com/in/jenilee-jenilee.13@gmail.com"}','Graphic Designer & DevOps Engineer','Tijuana','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 14,'Maurene','Maurene.14@gmail.com','M6e6iJskR4b2SPFiomqp045y4MORIXov','http://localhost:8080/file/profile/Maurene','IoFntEhiXDmngnjiXQYct','{"name":"Maurene Maurene.14@gmail.com","email":"maurene.maurene.14@gmail.com@example.com","twitter":"@maurene678","linkedin":"linkedin.com/in/maurene-maurene.14@gmail.com"}','SEO Specialist & Agile Coach','Maceió','[{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"}]' ),
    ( 15,'Annaliese','Annaliese.15@gmail.com','BLu7egMeqpzK3r50fH1SGi221MirQFPz','http://localhost:8080/file/profile/Annaliese','InPTXQLedIQXpEvKoHCVgYBBUpood','{"name":"Annaliese Annaliese.15@gmail.com","email":"annaliese.annaliese.15@gmail.com@example.com","twitter":"@annaliese170","linkedin":"linkedin.com/in/annaliese-annaliese.15@gmail.com"}','Actuary & Front-End Developer','Calgary','[{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"}]' ),
    ( 16,'Roslyn','Roslyn.16@gmail.com','rHO7XNCNZfNY6n1GWyHPcqIuMLopDAgD','http://localhost:8080/file/profile/Roslyn','REbUagjKoZNgEwfeEZwLTXytkRZcO','{"name":"Roslyn Roslyn.16@gmail.com","email":"roslyn.roslyn.16@gmail.com@example.com","twitter":"@roslyn760","linkedin":"linkedin.com/in/roslyn-roslyn.16@gmail.com"}','Actuary & Change Management Consultant','Monterrey','[{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"}]' ),
    ( 17,'Linet','Linet.17@gmail.com','XM6C2cpOT7awX7yI1mW0bnvj8XD7CErt','http://localhost:8080/file/profile/Linet','KiPygHObteoRTDcmUonGoSCHzUMaH','{"name":"Linet Linet.17@gmail.com","email":"linet.linet.17@gmail.com@example.com","twitter":"@linet140","linkedin":"linkedin.com/in/linet-linet.17@gmail.com"}','Database Administrator & Machine Learning Engineer','Virginia Beach','[{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"}]' ),
    ( 18,'Jackie','Jackie.18@gmail.com','BL23iPeZByZCcE1Irf3PsmqjyUEWE7ZA','http://localhost:8080/file/profile/Jackie','bqzTKPzCqHAbZLqEcBqWHGPKxlDMa','{"name":"Jackie Jackie.18@gmail.com","email":"jackie.jackie.18@gmail.com@example.com","twitter":"@jackie969","linkedin":"linkedin.com/in/jackie-jackie.18@gmail.com"}','Mobile App Developer & Public Relations Specialist','Lilongwe','[{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"}]' ),
    ( 19,'Randa','Randa.19@gmail.com','vmxPmeBLXszPSH62WN6lG5Bffesnpwfz','http://localhost:8080/file/profile/Randa','YoStVdIOGPWBzHPOs','{"name":"Randa Randa.19@gmail.com","email":"randa.randa.19@gmail.com@example.com","twitter":"@randa39","linkedin":"linkedin.com/in/randa-randa.19@gmail.com"}','UI/UX Designer & Agile Coach','Dammam','[{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"}]' ),
    ( 20,'Marnia','Marnia.20@gmail.com','d92YO400nBmTrjfUK2wKsIT2S0dsHz2b','http://localhost:8080/file/profile/Marnia','AnlsCKQSDHGI','{"name":"Marnia Marnia.20@gmail.com","email":"marnia.marnia.20@gmail.com@example.com","twitter":"@marnia478","linkedin":"linkedin.com/in/marnia-marnia.20@gmail.com"}','Supply Chain Manager & Web Developer','Bogor','[{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project4"}]' ),
    ( 21,'Renae','Renae.21@gmail.com','BMtqDf4N7gecsoILzzFrb3u2Jq8AEqEy','http://localhost:8080/file/profile/Renae','kwmajtFNAcT','{"name":"Renae Renae.21@gmail.com","email":"renae.renae.21@gmail.com@example.com","twitter":"@renae523","linkedin":"linkedin.com/in/renae-renae.21@gmail.com"}','Social Media Manager & Graphic Designer','Geneva','[{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 22,'Dorene','Dorene.22@gmail.com','nkkv5OWux7q3JTRKpexGlBLl281P5jpz','http://localhost:8080/file/profile/Dorene','vUyxP','{"name":"Dorene Dorene.22@gmail.com","email":"dorene.dorene.22@gmail.com@example.com","twitter":"@dorene633","linkedin":"linkedin.com/in/dorene-dorene.22@gmail.com"}','AI Specialist & Project Manager','Sri Jayawardenapura-Kotte','[{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"}]' ),
    ( 23,'Ofilia','Ofilia.23@gmail.com','sBMd1ElU5xoT0rUyUVyASQ7brRlCKLjZ','http://localhost:8080/file/profile/Ofilia','BUkkvNVFHrs','{"name":"Ofilia Ofilia.23@gmail.com","email":"ofilia.ofilia.23@gmail.com@example.com","twitter":"@ofilia767","linkedin":"linkedin.com/in/ofilia-ofilia.23@gmail.com"}','Actuary & Graphic Designer','Santa Cruz de la Sierra','[{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project4"}]' ),
    ( 24,'Alexine','Alexine.24@gmail.com','vmsQw8dSQXxVYjnSnYDhftcONZ6CPuzp','http://localhost:8080/file/profile/Alexine','SLBGhfnNFRFdVIe','{"name":"Alexine Alexine.24@gmail.com","email":"alexine.alexine.24@gmail.com@example.com","twitter":"@alexine213","linkedin":"linkedin.com/in/alexine-alexine.24@gmail.com"}','Operations Manager & Back-End Developer','Yokohama','[{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project4"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"}]' ),
    ( 25,'Nadine','Nadine.25@gmail.com','LAjDd5CLIgv2JjbZXy9dvrvsHmktuXNg','http://localhost:8080/file/profile/Nadine','uPxsQbLYoIjLezpYC','{"name":"Nadine Nadine.25@gmail.com","email":"nadine.nadine.25@gmail.com@example.com","twitter":"@nadine937","linkedin":"linkedin.com/in/nadine-nadine.25@gmail.com"}','DevOps Engineer & SEO Specialist','Pago Pago','[{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"}]' ),
    ( 26,'Gertrud','Gertrud.26@gmail.com','gYiwLz7IYYJTrmBPdGwKRPOnmJl69M6r','http://localhost:8080/file/profile/Gertrud','xvZ','{"name":"Gertrud Gertrud.26@gmail.com","email":"gertrud.gertrud.26@gmail.com@example.com","twitter":"@gertrud499","linkedin":"linkedin.com/in/gertrud-gertrud.26@gmail.com"}','Animator & Actuary','El Paso','[{"title":"Learning Nexus","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project4"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project3"}]' ),
    ( 27,'Dale','Dale.27@gmail.com','uh1X2bwn6ve5m12mUrmD1KmRQXpPRGtE','http://localhost:8080/file/profile/Dale','YyXrkzlRJUCimeuoHKCuUcMdBdVEEDN','{"name":"Dale Dale.27@gmail.com","email":"dale.dale.27@gmail.com@example.com","twitter":"@dale110","linkedin":"linkedin.com/in/dale-dale.27@gmail.com"}','Web Developer & Content Strategist','Manaus','[{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"}]' ),
    ( 28,'Marnia','Marnia.28@gmail.com','YBGoMYwCCmxdJ8F3icCX5CJPV4SX8PG2','http://localhost:8080/file/profile/Marnia','iwdfbwrYeMcpUGdpjkIaAhcmRQTCM','{"name":"Marnia Marnia.28@gmail.com","email":"marnia.marnia.28@gmail.com@example.com","twitter":"@marnia839","linkedin":"linkedin.com/in/marnia-marnia.28@gmail.com"}','Web Developer & Brand Manager','Murmansk','[{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project5"}]' ),
    ( 29,'Brianna','Brianna.29@gmail.com','ADmy4pVNPDoaEcjXY60pCP0Qy0AUzKoX','http://localhost:8080/file/profile/Brianna','FiFYlokjhPSVkJWTCjddJBCnmKYr','{"name":"Brianna Brianna.29@gmail.com","email":"brianna.brianna.29@gmail.com@example.com","twitter":"@brianna615","linkedin":"linkedin.com/in/brianna-brianna.29@gmail.com"}','Supply Chain Manager & Email Marketer','Denpasar','[{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"},{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"}]' ),
    ( 30,'Kary','Kary.30@gmail.com','Rb8vrASI5oyur1JkfiDISUnS7VDGb21x','http://localhost:8080/file/profile/Kary','gAeQPZVPajEyumtEC','{"name":"Kary Kary.30@gmail.com","email":"kary.kary.30@gmail.com@example.com","twitter":"@kary493","linkedin":"linkedin.com/in/kary-kary.30@gmail.com"}','Email Marketer & Market Researcher','Changchun','[{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project5"}]' ),
    ( 31,'Tori','Tori.31@gmail.com','qCetlVxuk88VLtA9sZLYvRqXYn2GQnbP','http://localhost:8080/file/profile/Tori','sfiRzcYRlO','{"name":"Tori Tori.31@gmail.com","email":"tori.tori.31@gmail.com@example.com","twitter":"@tori187","linkedin":"linkedin.com/in/tori-tori.31@gmail.com"}','PPC Specialist & DevOps Engineer','Sana''a','[{"title":"MentorConnect","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project5"}]' ),
    ( 32,'Sophia','Sophia.32@gmail.com','2bUFYKTBwYCdTnGHHdVoJcW1PRQbY7m7','http://localhost:8080/file/profile/Sophia','NgxRnrX','{"name":"Sophia Sophia.32@gmail.com","email":"sophia.sophia.32@gmail.com@example.com","twitter":"@sophia93","linkedin":"linkedin.com/in/sophia-sophia.32@gmail.com"}','Data Analyst & Scrum Master','Manila','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"}]' ),
    ( 33,'Anica','Anica.33@gmail.com','w2UxHn3g9nRKMUCaKP0RXGrob2TUOuAG','http://localhost:8080/file/profile/Anica','RxhcYHwKTNqAbLHjHyzVdlbQ','{"name":"Anica Anica.33@gmail.com","email":"anica.anica.33@gmail.com@example.com","twitter":"@anica579","linkedin":"linkedin.com/in/anica-anica.33@gmail.com"}','Product Manager & Communications Manager','Almaty','[{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"}]' ),
    ( 34,'Binny','Binny.34@gmail.com','YoIjYSpeem04MI0lZgxV6zzGCTbTVcF8','http://localhost:8080/file/profile/Binny','LqAZhLr','{"name":"Binny Binny.34@gmail.com","email":"binny.binny.34@gmail.com@example.com","twitter":"@binny73","linkedin":"linkedin.com/in/binny-binny.34@gmail.com"}','Game Developer & Digital Marketer','San Juan','[{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 35,'Marsiella','Marsiella.35@gmail.com','l1Ume49szVk77G16YGw6raU7sWAMJn5M','http://localhost:8080/file/profile/Marsiella','CmovvvWVIbPbQMQfxAnNiLSU','{"name":"Marsiella Marsiella.35@gmail.com","email":"marsiella.marsiella.35@gmail.com@example.com","twitter":"@marsiella507","linkedin":"linkedin.com/in/marsiella-marsiella.35@gmail.com"}','Supply Chain Manager & Software Engineer','Madrid','[{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"}]' ),
    ( 36,'Amelia','Amelia.36@gmail.com','aKHW4eXeWzd8peMGWzli1bXKudmIG0Ro','http://localhost:8080/file/profile/Amelia','hxZkAKrNZrmKMLXcutWhXniRiIXu','{"name":"Amelia Amelia.36@gmail.com","email":"amelia.amelia.36@gmail.com@example.com","twitter":"@amelia898","linkedin":"linkedin.com/in/amelia-amelia.36@gmail.com"}','PPC Specialist & Market Researcher','Sacramento','[{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project4"},{"title":"Learning Nexus","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 37,'Sophia','Sophia.37@gmail.com','NOEnrB6psPusFLkC1m64BIsxcHrYUxDK','http://localhost:8080/file/profile/Sophia','JZhvz','{"name":"Sophia Sophia.37@gmail.com","email":"sophia.sophia.37@gmail.com@example.com","twitter":"@sophia807","linkedin":"linkedin.com/in/sophia-sophia.37@gmail.com"}','Software Engineer & Project Manager','Hiroshima','[{"title":"MentorConnect","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"}]' ),
    ( 38,'Joane','Joane.38@gmail.com','mbWYpOklkFAMrdj0U4mGwiuZxoyJEyEn','http://localhost:8080/file/profile/Joane','GppoGiBbweKz','{"name":"Joane Joane.38@gmail.com","email":"joane.joane.38@gmail.com@example.com","twitter":"@joane722","linkedin":"linkedin.com/in/joane-joane.38@gmail.com"}','Data Engineer & Fashion Designer','Harbin','[]' ),
    ( 39,'Georgetta','Georgetta.39@gmail.com','3Ug3txEi4fEJERrgH3jNN6TEr9asqDw0','http://localhost:8080/file/profile/Georgetta','UCCUFUlXAsDnbyjhKeHtjWU','{"name":"Georgetta Georgetta.39@gmail.com","email":"georgetta.georgetta.39@gmail.com@example.com","twitter":"@georgetta257","linkedin":"linkedin.com/in/georgetta-georgetta.39@gmail.com"}','Email Marketer & Packaging Designer','Aberdeen','[{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 40,'Iseabal','Iseabal.40@gmail.com','nE4xPRcLujmEytwZktdTA9L2k6r3SS2N','http://localhost:8080/file/profile/Iseabal','jsGJkFatsUiOFHCluilWvYl','{"name":"Iseabal Iseabal.40@gmail.com","email":"iseabal.iseabal.40@gmail.com@example.com","twitter":"@iseabal373","linkedin":"linkedin.com/in/iseabal-iseabal.40@gmail.com"}','Web Designer & Change Management Consultant','Zanzibar City','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project4"}]' ),
    ( 41,'Glenda','Glenda.41@gmail.com','b8smyx5BbS17EQKr6boBB2l86dBZeVd6','http://localhost:8080/file/profile/Glenda','GNTtSyF','{"name":"Glenda Glenda.41@gmail.com","email":"glenda.glenda.41@gmail.com@example.com","twitter":"@glenda228","linkedin":"linkedin.com/in/glenda-glenda.41@gmail.com"}','Full-Stack Developer & Actuary','Berlin','[{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"}]' ),
    ( 42,'Millie','Millie.42@gmail.com','ir90AKGrOAAfwKHO9INgMp3oV97lHyHX','http://localhost:8080/file/profile/Millie','FUYoORRD','{"name":"Millie Millie.42@gmail.com","email":"millie.millie.42@gmail.com@example.com","twitter":"@millie367","linkedin":"linkedin.com/in/millie-millie.42@gmail.com"}','Game Developer & Brand Manager','Palikir','[{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"}]' ),
    ( 43,'Barbara','Barbara.43@gmail.com','44Yx7LdxemdBDvb5Bv87DmvmXt5O3xcS','http://localhost:8080/file/profile/Barbara','mZxLZkMTlRTZUGLqaGPYFtgWOD','{"name":"Barbara Barbara.43@gmail.com","email":"barbara.barbara.43@gmail.com@example.com","twitter":"@barbara844","linkedin":"linkedin.com/in/barbara-barbara.43@gmail.com"}','Statistician & Digital Marketer','Linz','[]' ),
    ( 44,'Maye','Maye.44@gmail.com','RcWcYeMgr5wPDCqlEwQsD8LeDqrcaDHb','http://localhost:8080/file/profile/Maye','QKby','{"name":"Maye Maye.44@gmail.com","email":"maye.maye.44@gmail.com@example.com","twitter":"@maye131","linkedin":"linkedin.com/in/maye-maye.44@gmail.com"}','Market Researcher & Product Manager','Basra','[{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"}]' ),
    ( 45,'Eve','Eve.45@gmail.com','kAnqFRiv2hnnByWzVMONqybRrNCH2cTE','http://localhost:8080/file/profile/Eve','slARcUvfhGaadBMIFRhJJRCqIxD','{"name":"Eve Eve.45@gmail.com","email":"eve.eve.45@gmail.com@example.com","twitter":"@eve161","linkedin":"linkedin.com/in/eve-eve.45@gmail.com"}','Packaging Designer & Game Developer','Tripoli','[{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project4"}]' ),
    ( 46,'Alisha','Alisha.46@gmail.com','mUbgAso3pLjxsgeUdVGVOUVCJWQKOHqz','http://localhost:8080/file/profile/Alisha','ypzNQFKWwgumexhTZpIeeHf','{"name":"Alisha Alisha.46@gmail.com","email":"alisha.alisha.46@gmail.com@example.com","twitter":"@alisha982","linkedin":"linkedin.com/in/alisha-alisha.46@gmail.com"}','UI/UX Designer & Brand Manager','Johor Bahru','[{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project1"}]' ),
    ( 47,'Tabbatha','Tabbatha.47@gmail.com','c4E8axJtRxjJWaRgybgn4tnBe8VTNzLx','http://localhost:8080/file/profile/Tabbatha','nxOvuXNFZDeKycsJtjPE','{"name":"Tabbatha Tabbatha.47@gmail.com","email":"tabbatha.tabbatha.47@gmail.com@example.com","twitter":"@tabbatha52","linkedin":"linkedin.com/in/tabbatha-tabbatha.47@gmail.com"}','Business Intelligence Analyst & Digital Marketer','Austin','[{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 48,'Eve','Eve.48@gmail.com','LQe79fUtERzxjQdjkaY0CL11Wy1e4hhT','http://localhost:8080/file/profile/Eve','NVFzYgIWgMdWiXSrOQazIAl','{"name":"Eve Eve.48@gmail.com","email":"eve.eve.48@gmail.com@example.com","twitter":"@eve27","linkedin":"linkedin.com/in/eve-eve.48@gmail.com"}','Public Relations Specialist & 3D Modeler','Rabi Island','[{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"}]' ),
    ( 49,'Gilligan','Gilligan.49@gmail.com','Kqq1Z0QTnRIR0SnL1ydDkyVevkTBYi0V','http://localhost:8080/file/profile/Gilligan','UFCBPipv','{"name":"Gilligan Gilligan.49@gmail.com","email":"gilligan.gilligan.49@gmail.com@example.com","twitter":"@gilligan904","linkedin":"linkedin.com/in/gilligan-gilligan.49@gmail.com"}','Graphic Designer & Data Analyst','Chaguanas','[{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"}]' ),
    ( 50,'Jobi','Jobi.50@gmail.com','LKaqBLj9MhbcuzlC4JsYAi4l23WDHDc7','http://localhost:8080/file/profile/Jobi','FIQUCJLeXVhubrMaqnNHrENVAogC','{"name":"Jobi Jobi.50@gmail.com","email":"jobi.jobi.50@gmail.com@example.com","twitter":"@jobi794","linkedin":"linkedin.com/in/jobi-jobi.50@gmail.com"}','Agile Coach & Web Developer','Winnipeg','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"}]' ),
    ( 51,'Berget','Berget.51@gmail.com','hJgWlTE7L5vGKhP0IXczBaVNLuhZT0a4','http://localhost:8080/file/profile/Berget','yNuaaiKTwsvdtbadSnZPpYgVKfoSss','{"name":"Berget Berget.51@gmail.com","email":"berget.berget.51@gmail.com@example.com","twitter":"@berget727","linkedin":"linkedin.com/in/berget-berget.51@gmail.com"}','Project Manager & Fashion Designer','Phuket (city)','[]' ),
    ( 52,'Alejandra','Alejandra.52@gmail.com','L6GHMLywLDhKfErCbLfpBGg5S07xtrdE','http://localhost:8080/file/profile/Alejandra','HorwEgmfb','{"name":"Alejandra Alejandra.52@gmail.com","email":"alejandra.alejandra.52@gmail.com@example.com","twitter":"@alejandra576","linkedin":"linkedin.com/in/alejandra-alejandra.52@gmail.com"}','Web Designer & Full-Stack Developer','Kobe','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 53,'Ericka','Ericka.53@gmail.com','ENWly1qPUjEKxiVmM32yjtLKU1dMTNdn','http://localhost:8080/file/profile/Ericka','JWnnThkrowKttVWTuVbwSDANr','{"name":"Ericka Ericka.53@gmail.com","email":"ericka.ericka.53@gmail.com@example.com","twitter":"@ericka98","linkedin":"linkedin.com/in/ericka-ericka.53@gmail.com"}','Machine Learning Engineer & Graphic Designer','Kano','[{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project5"}]' ),
    ( 54,'Paulita','Paulita.54@gmail.com','TNuNGdESjU7Y90ltlFQ5EGcEsAVPneO3','http://localhost:8080/file/profile/Paulita','JzIIIC','{"name":"Paulita Paulita.54@gmail.com","email":"paulita.paulita.54@gmail.com@example.com","twitter":"@paulita240","linkedin":"linkedin.com/in/paulita-paulita.54@gmail.com"}','Web Developer & Content Strategist','Roseau','[]' ),
    ( 55,'Carolina','Carolina.55@gmail.com','W7R45M05GA25F1g12BdgmPekiKgznTRV','http://localhost:8080/file/profile/Carolina','eiSnWijHXkvTssR','{"name":"Carolina Carolina.55@gmail.com","email":"carolina.carolina.55@gmail.com@example.com","twitter":"@carolina890","linkedin":"linkedin.com/in/carolina-carolina.55@gmail.com"}','PPC Specialist & Machine Learning Engineer','Shenyang','[{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"}]' ),
    ( 56,'Lenna','Lenna.56@gmail.com','XvExChvPqho0rW6wv31y1YHqZB9YhoPl','http://localhost:8080/file/profile/Lenna','NI','{"name":"Lenna Lenna.56@gmail.com","email":"lenna.lenna.56@gmail.com@example.com","twitter":"@lenna713","linkedin":"linkedin.com/in/lenna-lenna.56@gmail.com"}','Project Manager & Web Developer','Aberdeen','[{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project4"}]' ),
    ( 57,'Harrietta','Harrietta.57@gmail.com','Ftfxy6OThZEVfMnXcjMgNl8nlCZRXwA1','http://localhost:8080/file/profile/Harrietta','pbdTJqfoNlVoNfLdGHoAcJhvXUt','{"name":"Harrietta Harrietta.57@gmail.com","email":"harrietta.harrietta.57@gmail.com@example.com","twitter":"@harrietta804","linkedin":"linkedin.com/in/harrietta-harrietta.57@gmail.com"}','3D Modeler & Scrum Master','Havana','[{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"}]' ),
    ( 58,'Claresta','Claresta.58@gmail.com','tFojX9ZX4nbeSO3bNddMaim2sQyxP8Mx','http://localhost:8080/file/profile/Claresta','OVdwprIGnNFfmlgekPDPQSRbbgXVkRj','{"name":"Claresta Claresta.58@gmail.com","email":"claresta.claresta.58@gmail.com@example.com","twitter":"@claresta513","linkedin":"linkedin.com/in/claresta-claresta.58@gmail.com"}','Brand Strategist & Agile Coach','Madrid','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"}]' ),
    ( 59,'Dede','Dede.59@gmail.com','fMbXXbKoEjUen69AeoqWGnT7gxxinnU7','http://localhost:8080/file/profile/Dede','lMXtcQF','{"name":"Dede Dede.59@gmail.com","email":"dede.dede.59@gmail.com@example.com","twitter":"@dede511","linkedin":"linkedin.com/in/dede-dede.59@gmail.com"}','Front-End Developer & Data Scientist','Macapá','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"},{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"}]' ),
    ( 60,'Danika','Danika.60@gmail.com','RW2fls84b7NtdLPpNn5cWOQUFaYWNIlh','http://localhost:8080/file/profile/Danika','ljgX','{"name":"Danika Danika.60@gmail.com","email":"danika.danika.60@gmail.com@example.com","twitter":"@danika410","linkedin":"linkedin.com/in/danika-danika.60@gmail.com"}','Quantitative Analyst & Logistics Coordinator','Dili','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project5"}]' ),
    ( 61,'Lita','Lita.61@gmail.com','xlzYPHYuq8ZQU1zyk56gn8T2RMm79yDc','http://localhost:8080/file/profile/Lita','VRFZymBRoAeLbSrWtcpa','{"name":"Lita Lita.61@gmail.com","email":"lita.lita.61@gmail.com@example.com","twitter":"@lita472","linkedin":"linkedin.com/in/lita-lita.61@gmail.com"}','Market Researcher & Social Media Manager','Ndola','[{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"}]' ),
    ( 62,'Aimil','Aimil.62@gmail.com','KRiNXnQVO880Xp5hAn67BefwmbUygSvp','http://localhost:8080/file/profile/Aimil','fazKrArxrhaEsijbyfQVJq','{"name":"Aimil Aimil.62@gmail.com","email":"aimil.aimil.62@gmail.com@example.com","twitter":"@aimil805","linkedin":"linkedin.com/in/aimil-aimil.62@gmail.com"}','Data Scientist & Brand Strategist','Omsk','[]' ),
    ( 63,'Berta','Berta.63@gmail.com','YMwWSGJbBDJhIeaXDt9lJoDiYITmPuAT','http://localhost:8080/file/profile/Berta','ojbjxEDdOBMHgZBBkznB','{"name":"Berta Berta.63@gmail.com","email":"berta.berta.63@gmail.com@example.com","twitter":"@berta982","linkedin":"linkedin.com/in/berta-berta.63@gmail.com"}','Machine Learning Engineer & Market Researcher','Nanning','[{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project4"},{"title":"Learning Nexus","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"}]' ),
    ( 64,'Elvira','Elvira.64@gmail.com','Ao6ZVtno7NvQiYgDQ7CyDwDweLp0cYBb','http://localhost:8080/file/profile/Elvira','rKXFYixXvxJmosHoGgvajlrXRymZIb','{"name":"Elvira Elvira.64@gmail.com","email":"elvira.elvira.64@gmail.com@example.com","twitter":"@elvira241","linkedin":"linkedin.com/in/elvira-elvira.64@gmail.com"}','Animator & Database Administrator','Rosario','[]' ),
    ( 65,'Karly','Karly.65@gmail.com','KtYvlG7yf3ZXbfjv2RbHxYDllwXrgmFe','http://localhost:8080/file/profile/Karly','NOXzCminGmOVUovdDVaZQN','{"name":"Karly Karly.65@gmail.com","email":"karly.karly.65@gmail.com@example.com","twitter":"@karly927","linkedin":"linkedin.com/in/karly-karly.65@gmail.com"}','UI/UX Designer & Project Manager','Kota Bharu','[{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 66,'Sadie','Sadie.66@gmail.com','AmXXP6dor4ZmPiq2szviirMRXwd7CeSB','http://localhost:8080/file/profile/Sadie','ZoHLuIv','{"name":"Sadie Sadie.66@gmail.com","email":"sadie.sadie.66@gmail.com@example.com","twitter":"@sadie787","linkedin":"linkedin.com/in/sadie-sadie.66@gmail.com"}','Back-End Developer & SEO Specialist','Fortaleza','[{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"}]' ),
    ( 67,'Mireielle','Mireielle.67@gmail.com','wGPcL1gZw7D085ZVkNawB2r78EqPqeBk','http://localhost:8080/file/profile/Mireielle','NRUhAoiaGbTrWkctMzDkFHfchg','{"name":"Mireielle Mireielle.67@gmail.com","email":"mireielle.mireielle.67@gmail.com@example.com","twitter":"@mireielle111","linkedin":"linkedin.com/in/mireielle-mireielle.67@gmail.com"}','Packaging Designer & Database Administrator','Santa Cruz de Tenerife','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"}]' ),
    ( 68,'Elsie','Elsie.68@gmail.com','1G6tnTDvGRylrxAxDbLz45TFVmAwEDkr','http://localhost:8080/file/profile/Elsie','rNe','{"name":"Elsie Elsie.68@gmail.com","email":"elsie.elsie.68@gmail.com@example.com","twitter":"@elsie668","linkedin":"linkedin.com/in/elsie-elsie.68@gmail.com"}','Mobile App Developer & 3D Modeler','Kuwait City','[{"title":"MentorConnect","description":"A peer-to-peer learning network.","link":"https://example.com/project4"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"}]' ),
    ( 69,'Anthia','Anthia.69@gmail.com','jAM8PUzYoHOfryMQfLJ138uM1CDUDqWg','http://localhost:8080/file/profile/Anthia','hQxOOnihqJ','{"name":"Anthia Anthia.69@gmail.com","email":"anthia.anthia.69@gmail.com@example.com","twitter":"@anthia390","linkedin":"linkedin.com/in/anthia-anthia.69@gmail.com"}','Brand Manager & AI Specialist','Ciudad del Este','[{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"}]' ),
    ( 70,'Ebonee','Ebonee.70@gmail.com','r6Z3bCIihLznB6h4RDfxoavR3appFRRU','http://localhost:8080/file/profile/Ebonee','HjgVvKrUkoxUYYsQPy','{"name":"Ebonee Ebonee.70@gmail.com","email":"ebonee.ebonee.70@gmail.com@example.com","twitter":"@ebonee151","linkedin":"linkedin.com/in/ebonee-ebonee.70@gmail.com"}','3D Modeler & Project Manager','Cairns','[{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"}]' ),
    ( 71,'Flo','Flo.71@gmail.com','7LxiDW6X41rQVKXP4vvQjGTySvw0KE4s','http://localhost:8080/file/profile/Flo','puvinwH','{"name":"Flo Flo.71@gmail.com","email":"flo.flo.71@gmail.com@example.com","twitter":"@flo703","linkedin":"linkedin.com/in/flo-flo.71@gmail.com"}','Animator & Mobile App Developer','Quezon City','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"}]' ),
    ( 72,'Bernardine','Bernardine.72@gmail.com','eJASRtt81AqTvHHKUFo3IUdIvnYjOslh','http://localhost:8080/file/profile/Bernardine','volNKlPzMjoIvEhQnayMmsZRMw','{"name":"Bernardine Bernardine.72@gmail.com","email":"bernardine.bernardine.72@gmail.com@example.com","twitter":"@bernardine227","linkedin":"linkedin.com/in/bernardine-bernardine.72@gmail.com"}','Data Analyst & Agile Coach','Fortaleza','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"}]' ),
    ( 73,'Latisha','Latisha.73@gmail.com','fn8qHe6MoeUlfRcReUahEAB2krubVRDi','http://localhost:8080/file/profile/Latisha','FtwXDBhzHktyUYTEhtNkiljJCA','{"name":"Latisha Latisha.73@gmail.com","email":"latisha.latisha.73@gmail.com@example.com","twitter":"@latisha528","linkedin":"linkedin.com/in/latisha-latisha.73@gmail.com"}','Illustrator & Growth Hacker','Moroni','[{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"}]' ),
    ( 74,'Jobi','Jobi.74@gmail.com','BQqjuLN4suIjMaKIqQwWSu7bhAJnsX5D','http://localhost:8080/file/profile/Jobi','WXwzlfaTgJgJeooGVaJmlcTFLF','{"name":"Jobi Jobi.74@gmail.com","email":"jobi.jobi.74@gmail.com@example.com","twitter":"@jobi1","linkedin":"linkedin.com/in/jobi-jobi.74@gmail.com"}','Fashion Designer & Brand Manager','San Fernando','[{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"}]' ),
    ( 75,'Dolli','Dolli.75@gmail.com','5utfo8OKMkTQdCmXxcTd1e85KYp81mtD','http://localhost:8080/file/profile/Dolli','lUoGRdOzESUTKRPIcWHDvlncoJxCEGyD','{"name":"Dolli Dolli.75@gmail.com","email":"dolli.dolli.75@gmail.com@example.com","twitter":"@dolli198","linkedin":"linkedin.com/in/dolli-dolli.75@gmail.com"}','Scrum Master & SEO Specialist','Athens','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project2"}]' ),
    ( 76,'Ericka','Ericka.76@gmail.com','GxRNApZGIeFsMGN4UnEFSWS3hEwBGKW6','http://localhost:8080/file/profile/Ericka','yXwGCyqJyTsrxDZBKOvXNxbFCm','{"name":"Ericka Ericka.76@gmail.com","email":"ericka.ericka.76@gmail.com@example.com","twitter":"@ericka98","linkedin":"linkedin.com/in/ericka-ericka.76@gmail.com"}','Data Scientist & Social Media Manager','Vienna','[{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"A peer-to-peer learning network.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"}]' ),
    ( 77,'Candy','Candy.77@gmail.com','3gbQw83X4AWNd69DgPnR9uZ9nwNqG74m','http://localhost:8080/file/profile/Candy','TFfZDyLhLsfGARUCjaeFYfyYMfCgsOC','{"name":"Candy Candy.77@gmail.com","email":"candy.candy.77@gmail.com@example.com","twitter":"@candy450","linkedin":"linkedin.com/in/candy-candy.77@gmail.com"}','Web Designer & Agile Coach','Sukhumi','[{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project4"},{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"}]' ),
    ( 78,'Aili','Aili.78@gmail.com','4hd9mCq9E0wBnI9EK0h9NlOzVFcrdyw9','http://localhost:8080/file/profile/Aili','cwnWZPQoO','{"name":"Aili Aili.78@gmail.com","email":"aili.aili.78@gmail.com@example.com","twitter":"@aili358","linkedin":"linkedin.com/in/aili-aili.78@gmail.com"}','3D Modeler & Database Administrator','Oslo','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"}]' ),
    ( 79,'Alyda','Alyda.79@gmail.com','lDng3M6nveJz3Kfu6rgop0CVipUIUmOQ','http://localhost:8080/file/profile/Alyda','JbVeAShWacGIyPAcdhGSTGivt','{"name":"Alyda Alyda.79@gmail.com","email":"alyda.alyda.79@gmail.com@example.com","twitter":"@alyda817","linkedin":"linkedin.com/in/alyda-alyda.79@gmail.com"}','Full-Stack Developer & SEO Specialist','Puebla','[{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project2"},{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"}]' ),
    ( 80,'Madelle','Madelle.80@gmail.com','Od5I5rd9hdW2xmlb7fUg7WkfXG8Lc3ki','http://localhost:8080/file/profile/Madelle','kpVFeZIoriGKsobPEMsIkKokFumB','{"name":"Madelle Madelle.80@gmail.com","email":"madelle.madelle.80@gmail.com@example.com","twitter":"@madelle3","linkedin":"linkedin.com/in/madelle-madelle.80@gmail.com"}','Actuary & Supply Chain Manager','Perth','[]' ),
    ( 81,'Jany','Jany.81@gmail.com','AJVs17nMplVzfjrXRWqNHPaCEmJdk5TG','http://localhost:8080/file/profile/Jany','jrRT','{"name":"Jany Jany.81@gmail.com","email":"jany.jany.81@gmail.com@example.com","twitter":"@jany488","linkedin":"linkedin.com/in/jany-jany.81@gmail.com"}','Agile Coach & Data Analyst','Fukuoka','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"}]' ),
    ( 82,'Morganica','Morganica.82@gmail.com','sZueuhEwlXS7C5xNe9dGxKtPUIfDQShG','http://localhost:8080/file/profile/Morganica','dQwxRnRgkutVm','{"name":"Morganica Morganica.82@gmail.com","email":"morganica.morganica.82@gmail.com@example.com","twitter":"@morganica241","linkedin":"linkedin.com/in/morganica-morganica.82@gmail.com"}','Graphic Designer & Scrum Master','Konya','[]' ),
    ( 83,'Loree','Loree.83@gmail.com','XpEFQQUpJib2K1ujXqc4i2krb61yk1J4','http://localhost:8080/file/profile/Loree','YJFBJPBUrqWntgEqyWM','{"name":"Loree Loree.83@gmail.com","email":"loree.loree.83@gmail.com@example.com","twitter":"@loree149","linkedin":"linkedin.com/in/loree-loree.83@gmail.com"}','Content Strategist & Software Engineer','Lhasa','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project2"}]' ),
    ( 84,'Elka','Elka.84@gmail.com','BoyVSgCjq4zKj1iqHMdGZZP24dkpwxMg','http://localhost:8080/file/profile/Elka','aNtexvBjYJqzQLMTQKuaytWP','{"name":"Elka Elka.84@gmail.com","email":"elka.elka.84@gmail.com@example.com","twitter":"@elka667","linkedin":"linkedin.com/in/elka-elka.84@gmail.com"}','Back-End Developer & Operations Manager','Whitehorse','[{"title":"Expertise Exchange","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"}]' ),
    ( 85,'Marguerite','Marguerite.85@gmail.com','7rsW1t7MFCMyfJgjUd8eLuOKjNIkZXKS','http://localhost:8080/file/profile/Marguerite','fUZRviyOkLgyaXecYzPgT','{"name":"Marguerite Marguerite.85@gmail.com","email":"marguerite.marguerite.85@gmail.com@example.com","twitter":"@marguerite899","linkedin":"linkedin.com/in/marguerite-marguerite.85@gmail.com"}','Product Manager & Statistician','Vienna','[{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project4"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"}]' ),
    ( 86,'Juliane','Juliane.86@gmail.com','k8mNSsrPkhHqNY3Lnc0M7PgP5vi5KjYX','http://localhost:8080/file/profile/Juliane','xqtQl','{"name":"Juliane Juliane.86@gmail.com","email":"juliane.juliane.86@gmail.com@example.com","twitter":"@juliane964","linkedin":"linkedin.com/in/juliane-juliane.86@gmail.com"}','Social Media Manager & Data Analyst','Livingstone','[]' ),
    ( 87,'Berta','Berta.87@gmail.com','qOck7KO73xK7kJhuIJsv9uamzm5r0ups','http://localhost:8080/file/profile/Berta','mzClefxGvwlEIBYkopIpgkiG','{"name":"Berta Berta.87@gmail.com","email":"berta.berta.87@gmail.com@example.com","twitter":"@berta699","linkedin":"linkedin.com/in/berta-berta.87@gmail.com"}','Web Designer & Game Developer','New York City','[{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project3"}]' ),
    ( 88,'Cyndie','Cyndie.88@gmail.com','gwSsIbn9aqajRT7ZC7E93hKVyBqAyiQD','http://localhost:8080/file/profile/Cyndie','hQOOobhMyhnlmMFoHe','{"name":"Cyndie Cyndie.88@gmail.com","email":"cyndie.cyndie.88@gmail.com@example.com","twitter":"@cyndie147","linkedin":"linkedin.com/in/cyndie-cyndie.88@gmail.com"}','Statistician & Logistics Coordinator','Toulouse','[{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project1"}]' ),
    ( 89,'Fred','Fred.89@gmail.com','rFguhcNsi4RNr8hE7vPTbHT0Vhkm7AXR','http://localhost:8080/file/profile/Fred','aoWzLlzESGXRdhzGjlJAFdimPMCHlS','{"name":"Fred Fred.89@gmail.com","email":"fred.fred.89@gmail.com@example.com","twitter":"@fred327","linkedin":"linkedin.com/in/fred-fred.89@gmail.com"}','Brand Manager & Graphic Designer','Dili','[{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project3"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"}]' ),
    ( 90,'Camile','Camile.90@gmail.com','npWKuv8P51eJegmkchPCT4m0XxhYkZZK','http://localhost:8080/file/profile/Camile','yOTsdnflMJdTICOliZvoDcwINyccP','{"name":"Camile Camile.90@gmail.com","email":"camile.camile.90@gmail.com@example.com","twitter":"@camile941","linkedin":"linkedin.com/in/camile-camile.90@gmail.com"}','Mobile App Developer & Operations Manager','Iqaluit','[]' ),
    ( 91,'Roz','Roz.91@gmail.com','YXZ6NZkScMuPbwl2snFx01isIvhYXsg6','http://localhost:8080/file/profile/Roz','hzhqSNsduptFxQmxYcyrXBzfxxGfunBg','{"name":"Roz Roz.91@gmail.com","email":"roz.roz.91@gmail.com@example.com","twitter":"@roz341","linkedin":"linkedin.com/in/roz-roz.91@gmail.com"}','Graphic Designer & Growth Hacker','Tallinn','[{"title":"Learning Nexus","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"}]' ),
    ( 92,'Dulce','Dulce.92@gmail.com','TkKG3i5K3t6hkDSeFb0lJ96vqlhfDYC6','http://localhost:8080/file/profile/Dulce','QjiqhYxCdIORbrvlfXvkooBXkcOadY','{"name":"Dulce Dulce.92@gmail.com","email":"dulce.dulce.92@gmail.com@example.com","twitter":"@dulce938","linkedin":"linkedin.com/in/dulce-dulce.92@gmail.com"}','DevOps Engineer & Market Researcher','Tianjin','[{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"}]' ),
    ( 93,'Joceline','Joceline.93@gmail.com','LZLGipBI26v8bCxkOnpgqhnGrHOgIHzZ','http://localhost:8080/file/profile/Joceline','AjfuBgfXXmNHqLmuuZLbtrkXrsi','{"name":"Joceline Joceline.93@gmail.com","email":"joceline.joceline.93@gmail.com@example.com","twitter":"@joceline430","linkedin":"linkedin.com/in/joceline-joceline.93@gmail.com"}','Packaging Designer & Email Marketer','Ashgabat','[{"title":"MentorConnect","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"},{"title":"MentorConnect","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"}]' ),
    ( 94,'Blinni','Blinni.94@gmail.com','aA4gNSpMhe3qkd1Mm7vTBtjQVKLbdVmM','http://localhost:8080/file/profile/Blinni','fSDnEDVRReotryKD','{"name":"Blinni Blinni.94@gmail.com","email":"blinni.blinni.94@gmail.com@example.com","twitter":"@blinni608","linkedin":"linkedin.com/in/blinni-blinni.94@gmail.com"}','Animator & Data Engineer','Siem Reap','[{"title":"SkillSwap Platform","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"Expertise Exchange","description":"A peer-to-peer learning network.","link":"https://example.com/project1"}]' ),
    ( 95,'Vivia','Vivia.95@gmail.com','PTCdnYhMbIQ6pZvNbIuvRIgmrw4MxNa5','http://localhost:8080/file/profile/Vivia','GTovWg','{"name":"Vivia Vivia.95@gmail.com","email":"vivia.vivia.95@gmail.com@example.com","twitter":"@vivia427","linkedin":"linkedin.com/in/vivia-vivia.95@gmail.com"}','Product Manager & Data Scientist','Kyoto','[{"title":"KnowledgeHub","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project1"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"},{"title":"SkillSwap Platform","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project2"}]' ),
    ( 96,'Suzette','Suzette.96@gmail.com','RByXtBGFpFvaaqBPhCC0X6jhRskfIEok','http://localhost:8080/file/profile/Suzette','xjFfjQAmVyJuyatAiNhHOaoaxny','{"name":"Suzette Suzette.96@gmail.com","email":"suzette.suzette.96@gmail.com@example.com","twitter":"@suzette149","linkedin":"linkedin.com/in/suzette-suzette.96@gmail.com"}','Business Analyst & Fashion Designer','Da Nang','[{"title":"KnowledgeHub","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"SkillSwap Platform","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project3"},{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project1"}]' ),
    ( 97,'Melisent','Melisent.97@gmail.com','51rtoeMfbT4gwgaTOCmK5ELxSFW0Ny0o','http://localhost:8080/file/profile/Melisent','QpiKmuzn','{"name":"Melisent Melisent.97@gmail.com","email":"melisent.melisent.97@gmail.com@example.com","twitter":"@melisent48","linkedin":"linkedin.com/in/melisent-melisent.97@gmail.com"}','Full-Stack Developer & Scrum Master','Salt Lake City','[]' ),
    ( 98,'Edith','Edith.98@gmail.com','luLAXHyi089VOPCw036DqBfWupFnh4IJ','http://localhost:8080/file/profile/Edith','ANEdxTqwfuckNke','{"name":"Edith Edith.98@gmail.com","email":"edith.edith.98@gmail.com@example.com","twitter":"@edith682","linkedin":"linkedin.com/in/edith-edith.98@gmail.com"}','Growth Hacker & Brand Strategist','Brikama','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"Learning Nexus","description":"A peer-to-peer learning network.","link":"https://example.com/project3"},{"title":"MentorConnect","description":"Matches users with experts for specific tasks.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project5"},{"title":"KnowledgeHub","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project1"}]' ),
    ( 99,'Larine','Larine.99@gmail.com','AwDy7fjRwYIhuxiA0XhyNQKgcMlw2q23','http://localhost:8080/file/profile/Larine','OQKHwuSvRnMEZaoN','{"name":"Larine Larine.99@gmail.com","email":"larine.larine.99@gmail.com@example.com","twitter":"@larine318","linkedin":"linkedin.com/in/larine-larine.99@gmail.com"}','Quantitative Analyst & Motion Graphics Artist','Tashkent','[{"title":"Expertise Exchange","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project3"},{"title":"KnowledgeHub","description":"Matches users with experts for specific tasks.","link":"https://example.com/project2"}]' ),
    ( 100,'Sabina','Sabina.100@gmail.com','wW0UaZQ78Bw5MQweWHOh8dFd3AoCy8bo','http://localhost:8080/file/profile/Sabina','GcpHXTntolFFUkWFBfnTcMZLAUbGrjMg','{"name":"Sabina Sabina.100@gmail.com","email":"sabina.sabina.100@gmail.com@example.com","twitter":"@sabina839","linkedin":"linkedin.com/in/sabina-sabina.100@gmail.com"}','Growth Hacker & Business Analyst','Boa Vista','[{"title":"Expertise Exchange","description":"A platform for real-time knowledge exchange.","link":"https://example.com/project4"},{"title":"SkillSwap Platform","description":"Matches users with experts for specific tasks.","link":"https://example.com/project1"},{"title":"MentorConnect","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"Learning Nexus","description":"Facilitates one-on-one sessions for professional growth.","link":"https://example.com/project5"},{"title":"Expertise Exchange","description":"Connects mentors and mentees based on skill sets.","link":"https://example.com/project2"}]' );


INSERT INTO skills (name, description) VALUES
    ('Python', 'Programming language for general-purpose development'),
    ('JavaScript', 'Language for web development'),
    ('SQL', 'Database query language'),
    ('Graphic Design', 'Creating visual content'),
    ('Public Speaking', 'Skill for effective oral communication'),
    ('React', 'JavaScript library for building user interfaces'),
    ('Svelte', 'JavaScript framework for building web applications'),
    ('Tailwind CSS', 'Utility-first CSS framework for rapid development'),
    ('Node.js', 'JavaScript runtime for developing server-side applications'),
    ('C++', 'Programming language for developing operating systems and applications'),
    ('Java', 'Programming language for developing enterprise applications'),
    ('HTML/CSS', 'Markup language and styling language for web development'),
    ('Git', 'Version control system for tracking changes in source code'),
    ('Rust', 'Programming language for developing system software'),
    ('Kotlin', 'Programming language for developing Android applications'),
    ('TypeScript', 'Statically typed JavaScript superset'),
    ('Machine Learning', 'Development of algorithms for prediction and classificationification'),
    ('Computer Vision', 'Development of algorithms for image and video analysis'),
    ('Natural Language Processing', 'Development of algorithms for text analysis and generation'),
    ('Django', 'Python framework for developing web applications'),
    ('Flask', 'Micro web framework for developing web applications with Python'),
    ('Data Science', 'Extracting knowledge and insights from data');


INSERT INTO user_skills (user_id, skill_id, teaching_skill, verified) VALUES 
 ( 20,1,"Show how it's done",FALSE ),
 ( 79,9,"Show how it's done",FALSE ),
 ( 37,19,"Show how it's done",FALSE ),
 ( 13,15,"Show how it's done",FALSE ),
 ( 11,7,"Professor",TRUE ),
 ( 69,17,"Show how it's done",TRUE ),
 ( 24,2,"Professor",TRUE ),
 ( 4,12,"Professor",FALSE ),
 ( 52,4,"Professor",TRUE ),
 ( 90,2,"Explain in slight details",FALSE ),
 ( 28,3,"Explain in slight details",FALSE ),
 ( 64,16,"Give homework report on subject",TRUE ),
 ( 33,5,"Professor",TRUE ),
 ( 11,6,"Explain in slight details",TRUE ),
 ( 50,18,"Professor",TRUE ),
 ( 99,15,"Give homework report on subject",TRUE ),
 ( 84,20,"Show how it's done",TRUE ),
 ( 41,13,"Explain in slight details",TRUE ),
 ( 80,8,"Professor",TRUE ),
 ( 39,15,"Professor",FALSE ),
 ( 61,14,"Explain in slight details",TRUE ),
 ( 82,21,"Give homework report on subject",FALSE ),
 ( 27,18,"Give homework report on subject",TRUE ),
 ( 77,21,"Professor",TRUE ),
 ( 64,14,"Give homework report on subject",TRUE ),
 ( 54,10,"Explain in slight details",TRUE ),
 ( 15,20,"Explain in slight details",FALSE ),
 ( 87,14,"Explain in slight details",TRUE ),
 ( 52,1,"Explain in slight details",FALSE ),
 ( 45,2,"Show how it's done",FALSE ),
 ( 40,12,"Explain in slight details",TRUE ),
 ( 80,21,"Professor",TRUE ),
 ( 67,15,"Show how it's done",FALSE ),
 ( 55,20,"Give homework report on subject",FALSE ),
 ( 43,13,"Explain in slight details",FALSE ),
 ( 47,11,"Give homework report on subject",FALSE ),
 ( 55,13,"Show how it's done",TRUE ),
 ( 60,12,"Give homework report on subject",FALSE ),
 ( 15,7,"Give homework report on subject",TRUE ),
 ( 26,14,"Explain in slight details",TRUE ),
 ( 15,12,"Show how it's done",FALSE ),
 ( 7,5,"Give homework report on subject",TRUE ),
 ( 10,2,"Explain in slight details",TRUE ),
 ( 51,4,"Give homework report on subject",TRUE ),
 ( 73,7,"Professor",FALSE ),
 ( 90,8,"Show how it's done",FALSE ),
 ( 28,13,"Give homework report on subject",TRUE ),
 ( 86,20,"Professor",TRUE ),
 ( 26,11,"Explain in slight details",FALSE ),
 ( 65,2,"Explain in slight details",FALSE ),
 ( 90,3,"Give homework report on subject",FALSE ),
 ( 9,20,"Explain in slight details",TRUE ),
 ( 98,15,"Give homework report on subject",TRUE ),
 ( 62,17,"Show how it's done",FALSE ),
 ( 31,21,"Professor",FALSE ),
 ( 89,6,"Explain in slight details",TRUE ),
 ( 27,7,"Explain in slight details",FALSE ),
 ( 92,11,"Give homework report on subject",FALSE ),
 ( 94,20,"Professor",TRUE ),
 ( 1,17,"Give homework report on subject",TRUE ),
 ( 78,14,"Explain in slight details",FALSE ),
 ( 82,1,"Give homework report on subject",TRUE ),
 ( 49,7,"Explain in slight details",FALSE ),
 ( 83,19,"Explain in slight details",FALSE ),
 ( 66,9,"Explain in slight details",TRUE ),
 ( 48,2,"Explain in slight details",FALSE ),
 ( 7,3,"Show how it's done",TRUE ),
 ( 13,1,"Show how it's done",FALSE ),
 ( 73,11,"Professor",FALSE ),
 ( 78,21,"Show how it's done",TRUE ),
 ( 22,15,"Explain in slight details",TRUE ),
 ( 100,20,"Give homework report on subject",FALSE ),
 ( 23,13,"Professor",TRUE ),
 ( 87,9,"Professor",TRUE ),
 ( 1,8,"Explain in slight details",TRUE ),
 ( 51,5,"Show how it's done",TRUE ),
 ( 74,15,"Show how it's done",TRUE ),
 ( 74,16,"Explain in slight details",FALSE ),
 ( 43,3,"Show how it's done",FALSE ),
 ( 11,4,"Give homework report on subject",FALSE ),
 ( 98,5,"Professor",TRUE ),
 ( 71,13,"Show how it's done",FALSE ),
 ( 81,14,"Professor",FALSE ),
 ( 41,2,"Professor",TRUE ),
 ( 12,16,"Show how it's done",FALSE ),
 ( 12,9,"Show how it's done",TRUE ),
 ( 26,3,"Professor",TRUE ),
 ( 23,11,"Show how it's done",FALSE ),
 ( 27,21,"Give homework report on subject",FALSE ),
 ( 100,5,"Give homework report on subject",FALSE ),
 ( 99,7,"Professor",TRUE ),
 ( 26,21,"Professor",TRUE ),
 ( 1,13,"Give homework report on subject",FALSE ),
 ( 46,10,"Professor",FALSE ),
 ( 68,5,"Give homework report on subject",FALSE ),
 ( 50,17,"Give homework report on subject",FALSE ),
 ( 94,7,"Give homework report on subject",FALSE ),
 ( 52,10,"Give homework report on subject",TRUE ),
 ( 32,12,"Give homework report on subject",TRUE ),
 ( 75,19,"Give homework report on subject",FALSE );
Insert Into chats ( user1_id, user2_id, initiated_by) Values ( 1,10,1 ),
( 2,18,2 ),
( 3,40,3 ),
( 4,87,4 ),
( 5,16,5 ),
( 6,42,6 ),
( 7,84,7 ),
( 8,82,8 ),
( 9,59,9 ),
( 10,54,10 ),
( 11,15,11 ),
( 12,86,12 ),
( 13,79,13 ),
( 14,78,14 ),
( 15,29,15 ),
( 16,83,16 ),
( 17,93,17 ),
( 18,33,18 ),
( 19,48,19 ),
( 20,26,20 ),
( 21,64,21 ),
( 22,50,22 ),
( 23,70,23 ),
( 24,26,24 ),
( 25,11,25 ),
( 26,70,26 ),
( 27,39,27 ),
( 28,83,28 ),
( 29,91,29 ),
( 30,56,30 ),
( 31,86,31 ),
( 32,43,32 ),
( 33,1,33 ),
( 34,46,34 ),
( 35,70,35 ),
( 36,88,36 ),
( 37,23,37 ),
( 38,27,38 ),
( 39,76,39 ),
( 40,52,40 ),
( 41,96,41 ),
( 42,38,42 ),
( 43,27,43 ),
( 44,100,44 ),
( 45,2,45 ),
( 46,33,46 ),
( 47,40,47 ),
( 48,86,48 ),
( 49,42,49 ),
( 50,89,50 ),
( 51,68,51 ),
( 52,56,52 ),
( 53,88,53 ),
( 54,67,54 ),
( 55,23,55 ),
( 56,26,56 ),
( 57,97,57 ),
( 58,3,58 ),
( 59,61,59 ),
( 60,56,60 ),
( 61,38,61 ),
( 62,61,62 ),
( 63,10,63 ),
( 64,65,64 ),
( 65,1,65 ),
( 66,31,66 ),
( 67,99,67 ),
( 68,88,68 ),
( 69,39,69 ),
( 70,62,70 ),
( 71,1,71 ),
( 72,92,72 ),
( 73,77,73 ),
( 74,29,74 ),
( 75,90,75 ),
( 76,57,76 ),
( 77,44,77 ),
( 78,29,78 ),
( 79,20,79 ),
( 80,30,80 ),
( 81,50,81 ),
( 82,93,82 ),
( 83,19,83 ),
( 84,35,84 ),
( 85,26,85 ),
( 86,61,86 ),
( 87,62,87 ),
( 88,36,88 ),
( 89,71,89 ),
( 90,93,90 ),
( 91,51,91 ),
( 92,17,92 ),
( 93,63,93 ),
( 94,24,94 ),
( 95,34,95 ),
( 96,17,96 ),
( 97,23,97 ),
( 98,97,98 ),
( 99,69,99 ),
( 100,6,100 );



Insert Into messages ( chat_id, sender_id, content) Values ( 6,86,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 6,43,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 5,52,'hello' ),
    ( 8,48,'why' ),
    ( 10,97,'what' ),
    ( 2,87,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 4,92,'' ),
    ( 8,3,'hi' ),
    ( 10,6,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 8,34,'hi' ),
    ( 8,5,'hello' ),
    ( 3,7,'why' ),
    ( 2,87,'hello' ),
    ( 6,89,'why' ),
    ( 5,40,'' ),
    ( 9,71,'why' ),
    ( 6,83,'' ),
    ( 4,47,'when' ),
    ( 6,15,'what' ),
    ( 2,77,'what' ),
    ( 1,75,'when' ),
    ( 1,19,'' ),
    ( 7,96,'teach me that' ),
    ( 1,23,'why' ),
    ( 8,41,'oh my god' ),
    ( 8,27,'why' ),
    ( 10,9,'oh my god' ),
    ( 5,78,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 8,9,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 10,12,'no way' ),
    ( 9,99,'why' ),
    ( 8,62,'hello' ),
    ( 3,7,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 3,92,'hello' ),
    ( 1,87,'oh my god' ),
    ( 2,83,'no way' ),
    ( 4,47,'' ),
    ( 7,30,'hi' ),
    ( 6,77,'when' ),
    ( 7,13,'what' ),
    ( 9,95,'when' ),
    ( 3,29,'hi' ),
    ( 2,42,'what' ),
    ( 10,28,'oh my god' ),
    ( 8,78,'hello' ),
    ( 9,24,'hi' ),
    ( 4,14,'hello' ),
    ( 3,25,'hello' ),
    ( 3,14,'teach me that' ),
    ( 8,79,'when' ),
    ( 10,91,'why' ),
    ( 6,96,'when' ),
    ( 1,75,'hi' ),
    ( 4,47,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 10,83,'teach me that' ),
    ( 2,15,'what' ),
    ( 3,81,'hello' ),
    ( 1,89,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 6,24,'oh my god' ),
    ( 5,46,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 4,10,'' ),
    ( 2,48,'no way' ),
    ( 5,86,'no way' ),
    ( 5,80,'no way' ),
    ( 5,41,'hi' ),
    ( 3,24,'teach me that' ),
    ( 4,34,'when' ),
    ( 4,88,'what' ),
    ( 5,6,'teach me that' ),
    ( 3,19,'hi' ),
    ( 3,97,'what' ),
    ( 7,1,'no way' ),
    ( 10,99,'why' ),
    ( 9,27,'oh my god' ),
    ( 9,53,'oh my god' ),
    ( 9,46,'what' ),
    ( 3,7,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 4,58,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 1,44,'hi' ),
    ( 3,75,'hi' ),
    ( 4,11,'hello' ),
    ( 8,72,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 5,75,'hi' ),
    ( 7,74,'teach me that' ),
    ( 1,55,'when' ),
    ( 8,6,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 2,78,'oh my god' ),
    ( 5,53,'oh my god' ),
    ( 7,20,'what' ),
    ( 6,68,'' ),
    ( 9,87,'i beg you pleaseeeeeeeeeee!!!!' ),
    ( 5,82,'oh my god' ),
    ( 3,63,'what' ),
    ( 4,69,'oh my god' ),
    ( 7,50,'teach me that' ),
    ( 2,91,'teach me that' ),
    ( 2,72,'hello' ),
    ( 1,62,'hi' ),
    ( 2,17,'oh my god' ),
    ( 5,78,'why' );
