services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-app:latest
    container_name: go-app
    restart: unless-stopped
    init: true
    ports:
      - "8080:8080"  # Exposed by Dockerfile and main.go
    # env_file: ./.env  # Uncomment if .env file exists
    depends_on:
      - postgres
    networks:
      - appnet
    # If your app needs to run migrations, ensure bac.sql is used appropriately

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bac
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    # If you want to pre-load bac.sql, consider using a custom init script or mounting it to /docker-entrypoint-initdb.d/

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
    # Persistent storage for PostgreSQL
